---
sentry:
    image: sentry
    links:
        - postgres
        - redis

postgres:
    image: postgres
    environment:
        POSTGRES_USER: $db_user
        POSTGRES_PASSWORD: $db_pass

redis:
    image: redis
